export type BrandColorKey =
  | "brand1"
  | "brand2"
  | "brand3"
  | "brand4"
  | "brand5"
  | "brand6"
  | "brand7"
  | "brand8"
  | "brand9"
  | "brand10"
  | "brand11"
  | "brand12"

export type SecondaryColorKey =
  | "accent1"
  | "accent2"
  | "accent3"
  | "accent4"
  | "accent5"
  | "accent6"
  | "accent7"
  | "accent8"
  | "accent9"
  | "accent10"
  | "accent11"
  | "accent12"

export type AccentColorKey =
  | "secondary1"
  | "secondary2"
  | "secondary3"
  | "secondary4"
  | "secondary5"
  | "secondary6"
  | "secondary7"
  | "secondary8"
  | "secondary9"
  | "secondary10"
  | "secondary11"
  | "secondary12"

export type GrayColorKey =
  | "gray1"
  | "gray2"
  | "gray3"
  | "gray4"
  | "gray5"
  | "gray6"
  | "gray7"
  | "gray8"
  | "gray9"
  | "gray10"
  | "gray11"
  | "gray12"

export type OverlayColorKey =
  | "overlay1"
  | "overlay2"
  | "overlay3"
  | "overlay4"
  | "overlay5"
  | "overlay6"
  | "overlay7"
  | "overlay8"
  | "overlay9"
  | "overlay10"
  | "overlay11"
  | "overlay12"

export type SuccessColorKey =
  | "success1"
  | "success2"
  | "success3"
  | "success4"
  | "success5"
  | "success6"
  | "success7"
  | "success8"
  | "success9"
  | "success10"
  | "success11"
  | "success12"

export type DangerColorKey =
  | "danger1"
  | "danger2"
  | "danger3"
  | "danger4"
  | "danger5"
  | "danger6"
  | "danger7"
  | "danger8"
  | "danger9"
  | "danger10"
  | "danger11"
  | "danger12"

export type WarningColorKey =
  | "warning1"
  | "warning2"
  | "warning3"
  | "warning4"
  | "warning5"
  | "warning6"
  | "warning7"
  | "warning8"
  | "warning9"
  | "warning10"
  | "warning11"
  | "warning12"

export type MyColorKey =
  | "brand"
  | "accent"
  | "gray"
  | "overlay"
  | "success"
  | "danger"
  | "warning"
  | "info"
